### ISSUE TITLE
Requesting a new device ID + class question

### ISSUE THREAD

**Issue by HB9HIZ** [aprsorg/aprs-deviceid#179]
Hello, 

I'm David, HB9HIZ, and I'm developing an APRS-LoRa device (currently under development, everything will be open-sourced on GitHub). 

We are preparing a special contest (1st edition in 2025), using APRS to send messages to a high altitude balloon launch. The device will acknowledge the message (sort of QSL) and add some information (date, RSSI + Position of the balloon when the message was received, including altitude). This contest will be organized by our HAM association : HB4LO. 

My question is: What ‘class’ does this device fall into?

I'd like also to ask for the device id "APHLO1" for this device, what do you think ? 

So here are the query : 
-  tocall: APHLO1
   vendor: HB4LO
   model: HAB BOT 
   class : tracker/gadget?
   contact : david.perrin@hb9hiz.ch

Thanks a lot for your help and best regards, 

David HB9HIZ

**Comment by hessu** [comment]
Hi,

I'm assuming the device is the tracker which flies on the balloon, so I'd say it's a tracker.

As all new LoRa devices have been going in the APL* prefix lately, I've allocated this as **APLLO?** so that you can use APLLO1 for the first device, APLLO2... etc for future use. I hope that's alright.

Sorry for the slow reply.

**Comment by HB9HIZ** [comment]
Hello, 

Thanks a lot for the allocation ! APLLO? is perfect ! 

Best regards & all the best for this new year, 

David HB9HIZ
