### ISSUE TITLE
NEW APRS ID request: DM4RW/DL6MAA Teensy RPR TNC

### ISSUE THREAD

**Issue by ghost** [aprsorg/aprs-deviceid#69]
To all: APxRPR
Vendor: Robert (DM4RW) and Peter (DL6MAA)
Model: Teensy RPR TNC version X
Class: Tracker/TNC
OS: All OS
Contact: dm4rw@skywaves.de

This is a TNC/Tracker, newly developed for Robust Packet. Currently about 10 pieces are out in the field for testing purposes.

**Comment by hessu** [comment]
Hi,

The OS is for the operating system of the device/app itself, so I'm setting it to "embedded" for this one, assuming it's an embedded device.

The tocalls allocation is technically for prefixes, so the wildcard needs to go in the end instead of having one in the middle. I have allocated APRPR? for you, with a single-character wildcard in the end.

There is no tracker/tnc class and each device identifier may only go into one class; I've set it to "tracker" for this allocation now.

I hope this is alright for you; if you need to adjust it, please open a new ticket or reopen this one. Thank you!
